- fabric8/pom.xml
update to the latest greatest console
> update to the latest greatest console

- apiman/pom.xml
- apiman/src/main/java/io/fabric8/apiman/Fabric8ManagerApiMicroService.java
- apiman/src/main/resources-filtered/apimanui/apiman/f8-config.js
This is done by providing a custom config.js file with the appropriate settings.
> updated the apiman f8 microservice to use bearerTokenFromHash

- apiman-gateway/pom.xml
- apiman/pom.xml
And use also hawt-app-plugin for creating the proper classpath when starting.
> Update to fabric8/s2i-java base image

- packages/distro/pom.xml
added amqbroker to the list of microservices installed by the fabric8-ipaas distro
> added amqbroker to the list of microservices installed by the fabric8-ipaas distro

- amqbroker/pom.xml
- api-registry/pom.xml
- apiman-gateway/pom.xml
- apiman/pom.xml
- elasticsearch/pom.xml
- fabric8-msm/pom.xml
- fabric8mq-consumer/pom.xml
- fabric8mq-producer/pom.xml
- fabric8mq/pom.xml
- pom.xml
Upgrade to latest docker-maven-plugin 0.14.1
Andrea
> Upgrade to Docker-maven-plugin 0.14.1 with new groupId io.fabric8

- amqbroker/pom.xml
These two fixes allow me to successfully push the docker image and access the hawtio console for the amqbroker.
Most likely it needs more testing. Also perhaps the base image should be set for other modules in the parent pom.
> Amq fixes 

- fabric8mq/pom.xml
This makes hawtio work again on fabric8mq
(tests ran green, and tested with https://github.com/rparree/fabric8-demos/tree/master/fabric8-demo-mq )
> moved fabric8mq to use hawt and fabric8/s2i-java

- apiman/src/main/java/io/fabric8/apiman/ApimanStarter.java
- apiman/src/main/java/io/fabric8/apiman/KubernetesServiceCatalog.java
- apiman/src/test/java/io/fabric8/apiman/KubernetesServiceCatalogTest.java
https://github.com/fabric8io/fabric8-ipaas/issues/185
> updating the service annotation keys according to k8s spec

- apiman/src/main/java/io/fabric8/apiman/BearerTokenFilter.java
allowing access to Swagger.json/xml download https://github.com/fabric8io/fabric8-ipaas/issues/168
> allowing access to Swagger.json/xml download 

- apiman-gateway/src/main/java/io/fabric8/apiman/gateway/Fabric8GatewayMicroService.java
- apiman/src/main/java/io/fabric8/apiman/ApimanStarter.java
- pom.xml
Setting index prefix to apiman. and apiman-gateway. https://github.com/fabric8io/fabric8-ipaas/issues/205
Prefixing index with dot - https://github.com/fabric8io/fabric8-ipaas/issues/205
> upgrading apiman to latest release 1.2.3.RC1

- msg-gateway/src/main/java/io/fabric8/msg/gateway/ArtemisClient.java
- msg-gateway/src/main/java/io/fabric8/msg/gateway/MsgGateway.java
- msg-gateway/src/main/java/io/fabric8/msg/gateway/NotificationListener.java
- msg-gateway/src/main/java/io/fabric8/msg/gateway/Proxy.java
- msg-gateway/src/main/java/io/fabric8/msg/gateway/brokers/impl/KubernetesBrokerControl.java
- msg-gateway/src/main/resources/broker.xml
it was causing concurrent use of Session errors
> Remove JmsContext usuage - 

- amqbroker/pom.xml
This makes jolokia work again on amqbroker
> Configured amqbroker's jolokia for the java-jboss-openjdk8-jdk base img

- amqbroker/pom.xml
- msg-gateway/src/main/java/io/fabric8/msg/gateway/brokers/impl/EndpointWatcher.java
- msg-gateway/src/main/java/io/fabric8/msg/gateway/brokers/impl/KubernetesBrokerControl.java
- msg-gateway/src/main/java/io/fabric8/msg/gateway/brokers/impl/NamespaceName.java
- pom.xml
fixes #191 by excluding lots of test dependences from the hawtapp / image
> fixes #191 by excluding lots of test dependences from the hawtapp / image

- apiman/src/main/java/io/fabric8/apiman/Kubernetes2ApimanFilter.java
Fixing race condition where the service is still deploying. Now we wait with registering the into Apiman until the service is ready
> Adding an auto-registration bridge from k8s to apiman, #234

- artemis/pom.xml
> fix up the ports on artemis

- README.md
- release.groovy
add docs on the env var used to define messaging the service name
> add docs on the env var used to define messaging the service name

- apiman/pom.xml
Commented out the readinessProbe for now
> Setting ReadinessProbe to HTTPS in the ssl profile

- apiman-gateway/pom.xml
- apiman-gateway/src/main/resources-filtered/route-tls-passthrough.json
- apiman/pom.xml
- apiman/src/main/resources-filtered/route-tls-passthrough.json
- apiman/ssl.sh
making the route info filtered
> Apiman Manager & Gateway can't be accessed with https protocol #310

- apiman/src/main/java/io/fabric8/apiman/rest/Kubernetes2ApimanFilter.java
- message-gateway/src/main/java/io/fabric8/msg/gateway/brokers/impl/EndpointWatcher.java
- pom.xml
- zookeeper/src/main/java/io/fabric8/zookeeper/BuilderHelpers.java
- zookeeper/src/main/java/io/fabric8/zookeeper/ZooKeeperEnsembleCustomizer.java
> migrated to latest fabric8

- elasticsearch/src/test/java/io/fabric8/apps/elasticsearch/ElasticSearchKubernetesTest.java
- example-message-consumer/src/test/java/io/fabric8/apps/mq/consumer/MQConsumerKubernetesTest.java
- example-message-producer/src/test/java/io/fabric8/apps/producer/MQProducerKubernetesTest.java
- message-broker/src/test/java/io/fabric8/apps/artemis/ArtemisKubernetes.java
- message-gateway/src/test/java/io/fabric8/apps/msg/gateway/MsgGatewayKubernetes.java
- pom.xml
- sandbox/amqbroker/src/test/java/io/fabric8/apps/amq/AMQKubernetes.java
- sandbox/fabric8mq/src/test/java/io/fabric8/apps/mq/MQKubernetes.java
- sandbox/qpid-dispatch/src/test/java/io/fabric8/apps/qpid/QpidDispatchKubernetesTest.java
> upgraded to latest fabric8

- camel-master/README.md
- camel-master/src/main/java/io/fabric8/camel/master/KubernetesLock.java
lets polish the docs a little more and lets add a kind label to the ConfigMap
> lets polish the docs a little more and lets add a kind label to the ConfigMap

- camel-amq/ReadMe.md
> add buttons for the library

- camel-master/src/main/java/io/fabric8/camel/master/KubernetesLock.java
> fixes #402 thanks @valdar

- camel-master/src/test/java/io/fabric8/camel/master/KubernetesLockTest.java
- pom.xml
> Fixed KubernetesLockTest for the Kubernetes-client 2.6.3 upgrade
